---

# This is the main site YAML file, which will deploy the whole LAMP application
# Stack

- name: Apply common configuration to all servers
  hosts: all
  remote_user: root

  roles:

    - common

- name: Configure and Deploy Web Servers, along with deploying the Mediawiki Application Code
  hosts: webservers
  remote_user: root

  roles:

    - web

- name: Configure and Deploy MySQL (MariaDB) Database
  hosts: dbservers
  remote_user: root

  roles:

    - db
